# Generated by Django 4.2.4 on 2023-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('discount', models.TextField(null=True)),
                ('timeid', models.TextField()),
            ],
        ),
    ]
