# Generated by Django 4.2.4 on 2023-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozonparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timeid',
            field=models.IntegerField(),
        ),
    ]
