# Generated by Django 4.2.4 on 2023-08-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozonparser', '0002_alter_product_timeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timeid',
            field=models.BigIntegerField(),
        ),
    ]
