# Generated by Django 4.2.4 on 2023-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozonparser', '0003_alter_product_timeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
